kind: Pod
apiVersion: v1
metadata:
  name: grafana
spec:
  containers:
  - name: grafana
    image: docker.io/grafana/grafana
    ports:
    - containerPort: 3000
      hostPort: 3000
    volumeMounts:
    - name: grafana-data
      mountPath: /home/pi/homelab/podman/pods/grafana
  volumes:
  - name: grafana-data
    hostPath:
      path: /home/pi/homelab/podman/pods/grafana