kind: Pod
apiVersion: v1
metadata:
  name: nextcloudpi
spec:
  containers:
  - name: nextcloudpi
    image: docker.io/ownyourbits/nextcloudpi:latest
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    volumeMounts:
    - name: ncp-data
      mountPath: /data
    - name: ncp-config
      mountPath: /config
  volumes:
  - name: ncp-data
    hostPath:
      path: /home/pi/homelab/podman/pods/nextcloudpi/data
  - name: ncp-config
    hostPath:
      path: /home/pi/homelab/podman/pods/nextcloudpi/config